//! The key handling engine: physical key events in, inputs to send out.
//!
//! Ported from the D version's `keyboardHook` and `handleKeyEvent` (source/reneo.d). The engine is a pure state
//! machine: everything it needs from Windows goes through [`Platform`], and everything it wants to happen goes into
//! an [`Output`]. That makes it testable without Windows, and keeps the hook path free of allocations once the
//! output buffers are warm.

use std::collections::HashMap;

use crate::compose::{Compose, ComposeResult};
use crate::keys::{vk, ForcedModifiers, ModKind, Modifier, Scancode, Side, NATIVE_MODIFIERS};
use crate::keysym::{Keysyms, KEYSYM_VOID};
use crate::layout::{KeyAction, Layout};

// ─── Interface ─────────────────────────────────────────────────────────────────

/// A key event as seen by the low-level keyboard hook
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct KeyEvent {
    pub vk: u16,
    pub scan: Scancode,
    pub down: bool,
    /// Generated by software (SendInput) instead of a physical key
    pub injected: bool,
}

/// Native key combination that produces a character
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct CharKey {
    pub vk: u16,
    pub scan: u16,
    pub shift: bool,
    /// Needs AltGr, which is sent as LCtrl+RAlt
    pub altgr: bool,
}

/// What the engine needs to know from the operating system
pub trait Platform {
    /// Is Capslock toggled on?
    fn capslock(&self) -> bool;
    /// Is Kana toggled on? (kbdneo uses Kana as a permanent layer 4 lock)
    fn kana(&self) -> bool;
    /// Scancode of a virtual key in the native layout, 0 if the native layout doesn't have it
    fn vk_to_scan(&self, vk: u16) -> u16;
    /// Native key combination that produces the character directly, `None` if it must be sent as Unicode
    /// (not in the native layout, only as dead key, or needs exotic modifiers)
    fn char_key(&mut self, c: char, capslock: bool) -> Option<CharKey>;
}

/// One input event to inject
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Input {
    Key { vk: u16, scan: Scancode, down: bool },
    /// One UTF-16 code unit sent as Unicode packet (VK_PACKET)
    Unicode { unit: u16, down: bool },
    /// Primary mouse button
    MouseLeft { down: bool },
}

/// Something the rest of the application should react to, outside of the hook
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Notice {
    /// The layer shown by the on-screen keyboard or the Capslock state changed
    OskChanged,
    /// A state shown in the tray changed (Mod4 lock)
    StateChanged,
    ToggleOsk,
    ToggleOneHandedMode,
}

/// Inputs to send, grouped in batches. Each batch must be sent with one SendInput call, so that no other input can
/// get in between (e.g. the modifiers and the key of a combination).
#[derive(Debug)]
pub struct Output {
    pub inputs: Vec<Input>,
    batch_ends: Vec<usize>,
    pub notices: Vec<Notice>,
}

impl Default for Output {
    fn default() -> Self {
        Output { inputs: Vec::with_capacity(128), batch_ends: Vec::with_capacity(32), notices: Vec::with_capacity(8) }
    }
}

impl Output {
    pub fn clear(&mut self) {
        self.inputs.clear();
        self.batch_ends.clear();
        self.notices.clear();
    }

    pub fn batches(&self) -> impl Iterator<Item = &[Input]> {
        let mut start = 0;
        self.batch_ends.iter().map(move |&end| {
            let batch = &self.inputs[start..end];
            start = end;
            batch
        })
    }

    fn end_batch(&mut self) {
        if self.batch_ends.last() != Some(&self.inputs.len()) {
            self.batch_ends.push(self.inputs.len());
        }
    }

    fn notice(&mut self, notice: Notice) {
        if !self.notices.contains(&notice) {
            self.notices.push(notice);
        }
    }
}

#[derive(Clone, Debug)]
pub struct EngineConfig {
    /// Hide Mod3/Mod4 events from programs in extension mode (workaround for Qt/GTK, neo-layout issue 510)
    pub filter_neo_modifiers: bool,
    /// Pressing both Mod4 keys locks layer 4
    pub enable_mod4_lock: bool,
    /// One-handed mode: holding this key mirrors the keyboard
    pub mirror_key: Scancode,
    pub mirror_map: HashMap<Scancode, Scancode>,
}

impl Default for EngineConfig {
    fn default() -> Self {
        EngineConfig {
            filter_neo_modifiers: true,
            enable_mod4_lock: true,
            mirror_key: Scancode::new(0x39, false),
            mirror_map: HashMap::new(),
        }
    }
}

// ─── State ─────────────────────────────────────────────────────────────────────

const SC_FAKE_LSHIFT: u16 = 0x22A;
const SC_FAKE_RSHIFT: u16 = 0x236;
const SC_FAKE_LCTRL: u16 = 0x21D;
const SC_CAPSLOCK: Scancode = Scancode::new(0x3A, false);
const SC_NUMLOCK: Scancode = Scancode::new(0x45, true);

/// Refers to the key of a layout on a layer, instead of copying it (NeoKey contains a String)
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct KeyRef {
    layout: usize,
    scan: Scancode,
    layer: usize,
}

/// Physical keys currently holding one modifier. Usually one, rarely two keys map to the same modifier.
#[derive(Clone, Copy, Debug, Default)]
struct ModifierKeys([Option<Scancode>; 4]);

impl ModifierKeys {
    fn insert(&mut self, scan: Scancode) {
        if self.0.contains(&Some(scan)) {
            return;
        }
        if let Some(slot) = self.0.iter_mut().find(|s| s.is_none()) {
            *slot = Some(scan);
        }
    }

    fn remove(&mut self, scan: Scancode) {
        for slot in self.0.iter_mut().filter(|s| **s == Some(scan)) {
            *slot = None;
        }
    }

    fn is_empty(&self) -> bool {
        self.0.iter().all(Option::is_none)
    }
}

fn modifier_slot(modifier: Modifier) -> usize {
    let kind = match modifier.kind {
        ModKind::Shift => 0,
        ModKind::Ctrl => 1,
        ModKind::Alt => 2,
        ModKind::Mod3 => 3,
        ModKind::Mod4 => 4,
        ModKind::Mod5 => 5,
        ModKind::Mod6 => 6,
        ModKind::Mod7 => 7,
        ModKind::Mod8 => 8,
        ModKind::Mod9 => 9,
    };
    kind * 2 + usize::from(modifier.side == Side::Right)
}

pub struct Engine {
    pub config: EngineConfig,
    layouts: Vec<Layout>,
    keysyms: Keysyms,
    compose: Compose,
    active: Option<usize>,
    /// Replace the native layout completely (as opposed to extending a native Neo driver)
    standalone: bool,
    one_handed: bool,

    /// Physical keys holding each modifier ("natural modifier state")
    held_modifiers: [ModifierKeys; 20],
    /// Native modifiers currently forced up or down by a held mapping
    forced: ForcedModifiers,
    capslock: bool,
    mod4_lock: bool,
    previous_patched_layer: usize,
    osk_layer: usize,
    /// What we sent for each held physical key, so that the release matches the press
    held_keys: Vec<(Scancode, KeyRef)>,
    /// The last pressed key: only its release resets the forced modifiers
    last_key: Option<KeyRef>,

    mirror_key_held: bool,
    /// Keys were mirrored while the mirror key was held, so it doesn't produce its own key
    eat_mirror_key: bool,
    /// Original scancodes of keys pressed while the mirror key is held
    primed_keys: Vec<Scancode>,
    /// The last event was a dual state numpad key up with held Shift: eat the next Shift down
    expect_fake_shift_down: bool,
}

impl Engine {
    pub fn new(layouts: Vec<Layout>, keysyms: Keysyms, compose: Compose, config: EngineConfig) -> Engine {
        Engine {
            config,
            layouts,
            keysyms,
            compose,
            active: None,
            standalone: false,
            one_handed: false,
            held_modifiers: [ModifierKeys::default(); 20],
            forced: ForcedModifiers::NONE,
            capslock: false,
            mod4_lock: false,
            previous_patched_layer: 1,
            osk_layer: 1,
            held_keys: Vec::with_capacity(32),
            last_key: None,
            mirror_key_held: false,
            eat_mirror_key: false,
            primed_keys: Vec::with_capacity(16),
            expect_fake_shift_down: false,
        }
    }

    // ─── Accessors ─────────────────────────────────────────────────────────────

    pub fn layouts(&self) -> &[Layout] {
        &self.layouts
    }

    pub fn active_layout(&self) -> Option<&Layout> {
        self.active.map(|i| &self.layouts[i])
    }

    /// Selects the layout by index into [`Engine::layouts`], returns whether it changed
    pub fn set_active_layout(&mut self, index: Option<usize>) -> bool {
        let changed = self.active != index;
        self.active = index;
        changed
    }

    pub fn standalone(&self) -> bool {
        self.standalone
    }

    pub fn set_standalone(&mut self, standalone: bool) {
        self.standalone = standalone;
    }

    pub fn one_handed(&self) -> bool {
        self.one_handed
    }

    pub fn set_one_handed(&mut self, one_handed: bool) {
        self.one_handed = one_handed;
    }

    pub fn mod4_lock(&self) -> bool {
        self.mod4_lock
    }

    pub fn capslock(&self) -> bool {
        self.capslock
    }

    /// Layer to show in the on-screen keyboard (Capslock already applied to layers 1 and 2)
    pub fn osk_layer(&self) -> usize {
        self.osk_layer
    }

    pub fn is_modifier_held(&self, modifier: Modifier) -> bool {
        !self.held_modifiers[modifier_slot(modifier)].is_empty()
    }

    fn is_kind_held(&self, kind: ModKind) -> bool {
        self.is_modifier_held(Modifier { kind, side: Side::Left }) || self.is_modifier_held(Modifier { kind, side: Side::Right })
    }

    /// Keys whose events don't reveal typed text: modifiers, function, navigation and media keys.
    /// Events of all other keys must be redacted in shareable logs.
    pub fn is_non_text_key(&self, vk_code: u16, scan: Scancode) -> bool {
        if self.active_layout().is_some_and(|layout| layout.modifiers.contains_key(&scan)) {
            return true;
        }
        matches!(vk_code,
            vk::SHIFT..=vk::CAPITAL          // Shift, Ctrl, Alt, Pause, Capslock
            | vk::ESCAPE
            | vk::PRIOR..=vk::DOWN           // Page up/down, End, Home, arrows
            | vk::INSERT | vk::DELETE | 0x2C // Snapshot
            | 0x5B..=0x5D                    // Windows keys, Apps
            | 0x70..=0x87                    // F1 to F24
            | vk::NUMLOCK | 0x91             // Scroll lock
            | vk::LSHIFT..=0xB7              // left/right modifiers, browser and media keys
        )
    }

    // ─── State resets ──────────────────────────────────────────────────────────

    /// Forgets all keys and modifiers believed to be held, and partial compose and one-handed sequences.
    /// Lock states (Capslock, Mod4 lock) are kept.
    pub fn forget_held_keys(&mut self) {
        self.held_modifiers = [ModifierKeys::default(); 20];
        self.held_keys.clear();
        self.forced = ForcedModifiers::NONE;
        self.mirror_key_held = false;
        self.eat_mirror_key = false;
        self.primed_keys.clear();
        self.expect_fake_shift_down = false;
        self.previous_patched_layer = 1;
        self.compose.reset();
    }

    /// Called when key up events might have been lost (secure desktop, elevated window, removed hook): releases
    /// everything programs might see as pressed because of us, then forgets it (#94)
    pub fn release_all_held_keys(&mut self, platform: &mut dyn Platform, out: &mut Output) {
        let held = std::mem::take(&mut self.held_keys);
        for &(scan, key) in &held {
            self.send_key(key, scan, false, platform, out);
        }
        self.held_keys = held;

        for modifier in NATIVE_MODIFIERS {
            if self.is_modifier_held(modifier) || self.forced.get(modifier) == Some(true) {
                self.send_modifier(modifier, false, out);
            }
        }
        self.forget_held_keys();
    }

    /// Resets everything that could lead to unwanted locks, when the hook becomes active
    pub fn reset_states(&mut self, platform: &mut dyn Platform, out: &mut Output) {
        self.forget_held_keys();
        self.capslock = false;
        self.mod4_lock = false;
        if platform.capslock() {
            self.send_vk(vk::CAPITAL, Scancode::new(0, false), true, out);
            self.send_vk(vk::CAPITAL, Scancode::new(0, false), false, out);
        }
        // kbdneo uses Kana as a permanent layer 4 lock
        if platform.kana() {
            self.send_vk(vk::KANA, Scancode::new(0, false), true, out);
            self.send_vk(vk::KANA, Scancode::new(0, false), false, out);
        }
    }

    // ─── Hook entry point ──────────────────────────────────────────────────────

    /// Handles one event of the low-level keyboard hook. Returns whether the original event must be swallowed.
    pub fn handle(&mut self, event: &KeyEvent, platform: &mut dyn Platform, out: &mut Output) -> bool {
        let Some(layout_index) = self.active else { return false };
        let KeyEvent { vk: vk_code, scan, down, injected } = *event;

        // Ignore simulated key presses, from us and from other programs
        if vk_code == vk::PACKET || injected {
            return false;
        }

        // Numpad 0-9 and separator are "dual state" keys: scancodes 0x47 to 0x53 without 0x4A and 0x4E
        let dual_state_numpad = !scan.extended && (0x47..=0x53).contains(&scan.code) && scan.code != 0x4A && scan.code != 0x4E;

        // With Numlock on, Shift plus a dual state numpad key makes the driver insert fake Shift events to lift and
        // repress Shift. Fake ups always have a special scancode, the downs only sometimes. So: eat everything with
        // the fake scancode, and after a dual state numpad key up with Shift held expect one Shift down to eat.
        if self.expect_fake_shift_down {
            if down && (vk_code == vk::LSHIFT || vk_code == vk::RSHIFT) {
                return true;
            }
            self.expect_fake_shift_down = false;
        }
        if scan.code == SC_FAKE_LSHIFT || scan.code == SC_FAKE_RSHIFT {
            return true;
        }
        if dual_state_numpad && !down && self.is_kind_held(ModKind::Shift) {
            self.expect_fake_shift_down = true;
        }

        // Windows adds a fake LCtrl to the physical AltGr key, which is Mod4 here. (An injected AltGr's fake LCtrl
        // is marked as injected and passed above.)
        if scan.code == SC_FAKE_LCTRL {
            return true;
        }

        if down && self.is_kind_held(ModKind::Mod3) {
            if vk_code == vk::F1 {
                out.notice(Notice::ToggleOsk);
                return true;
            }
            if vk_code == vk::F10 {
                out.notice(Notice::ToggleOneHandedMode);
                return true;
            }
        }

        // Filtering the Numlock key would toggle the Numlock state without changing the LED. Pressing it a few more
        // times internally resolves that (like AutoHotkey). Unmapped Numlock keys pass unaffected.
        if vk_code == vk::NUMLOCK && down && self.layouts[layout_index].map.contains_key(&scan) {
            for key_down in [false, true, false, true] {
                self.send_vk(vk::NUMLOCK, SC_NUMLOCK, key_down, out);
            }
        }

        if self.one_handed {
            if let Some(eat) = self.one_handed_mode(scan, down, platform, out) {
                return eat;
            }
        }

        self.handle_key(scan, down, platform, out)
    }

    /// One-handed mode (M: mirror key, A, B: other keys, A': A mirrored, D/U: down/up):
    /// 1. `MD MU` gives `MD MU` on release (unused mirror key)
    /// 2. `AD MD AU MU` gives `AD AU MD MU` (keys pressed before the mirror key aren't mirrored)
    /// 3. `MD AD AU MU` gives `A'D A'U` (keys pressed and released while mirroring are mirrored, M is swallowed)
    /// 4. `MD AD BD MU AU BU` gives `MD MU AD BD AU BU` (keys still held when M is released are sent unmirrored)
    ///
    /// Returns `None` if the event isn't handled here.
    fn one_handed_mode(&mut self, scan: Scancode, down: bool, platform: &mut dyn Platform, out: &mut Output) -> Option<bool> {
        if scan == self.config.mirror_key {
            self.mirror_key_held = down;
            if !down {
                if !self.eat_mirror_key {
                    self.handle_key(scan, true, platform, out);
                    self.handle_key(scan, false, platform, out);
                }
                self.eat_mirror_key = false;

                let primed = std::mem::take(&mut self.primed_keys);
                for &key in &primed {
                    self.handle_key(key, true, platform, out);
                }
                self.primed_keys = primed;
                self.primed_keys.clear();
            }
            return Some(true);
        }

        if self.mirror_key_held {
            if let Some(&mirrored) = self.config.mirror_map.get(&scan) {
                let primed_index = self.primed_keys.iter().position(|&k| k == scan);
                if down {
                    if primed_index.is_none() {
                        self.primed_keys.push(scan);
                    }
                    return Some(true);
                }
                if let Some(index) = primed_index {
                    self.primed_keys.remove(index);
                    self.handle_key(mirrored, true, platform, out);
                    self.handle_key(mirrored, false, platform, out);
                    self.eat_mirror_key = true;
                    return Some(true);
                }
            }
        }
        None
    }

    /// Updates modifier and layer state and sends the mapped key. Returns whether the original event is swallowed.
    fn handle_key(&mut self, scan: Scancode, down: bool, platform: &mut dyn Platform, out: &mut Output) -> bool {
        let layout_index = self.active.expect("handle_key without layout");

        // All numpad keys including numpad Enter and Numlock
        let numpad_key = (!scan.extended && (0x47..=0x53).contains(&scan.code))
            || scan == Scancode::new(0x35, true)
            || scan == Scancode::new(0x37, false)
            || scan == Scancode::new(0x1C, true)
            || scan == Scancode::new(0x45, true);

        // Modifier keys: update the natural modifier state, locks, and send native modifiers. They return only after
        // the layer was updated, so the OSK follows.
        let mut modifier_eaten = None;
        if let Some(&modifier) = self.layouts[layout_index].modifiers.get(&scan) {
            let neo_modifier = !modifier.kind.is_native();

            if down {
                // Both Shift keys toggle Capslock
                if modifier.kind == ModKind::Shift && !self.is_modifier_held(modifier) && self.is_modifier_held(opposite(modifier)) {
                    self.send_vk(vk::CAPITAL, SC_CAPSLOCK, true, out);
                    self.send_vk(vk::CAPITAL, SC_CAPSLOCK, false, out);
                }
                // Both Mod4 keys toggle Mod4 lock. Disabling always works.
                if modifier.kind == ModKind::Mod4
                    && !self.is_modifier_held(modifier)
                    && self.is_modifier_held(opposite(modifier))
                    && (self.config.enable_mod4_lock || self.mod4_lock)
                {
                    self.mod4_lock = !self.mod4_lock;
                    out.notice(Notice::StateChanged);
                }
            }

            // In standalone and one-handed mode every modifier event is replaced. In extension mode only Neo
            // modifiers are swallowed (if configured), native ones pass.
            let eat = self.standalone || self.one_handed || (neo_modifier && self.config.filter_neo_modifiers);
            let send_own = eat && !neo_modifier;

            let slot = modifier_slot(modifier);
            if down {
                self.held_modifiers[slot].insert(scan);
                if send_own {
                    self.send_modifier(modifier, true, out);
                }
            } else {
                self.held_modifiers[slot].remove(scan);
                // Only release if this was the last key holding the modifier and no mapping forces it down
                if send_own && !self.is_modifier_held(modifier) && self.forced.get(modifier) != Some(true) {
                    self.send_modifier(modifier, false, out);
                }
            }
            modifier_eaten = Some(eat);
        }

        let capslock = platform.capslock();
        let capslock_changed = capslock != self.capslock;
        self.capslock = capslock;

        // The first layer whose modifier requirements match
        let layout = &self.layouts[layout_index];
        let mut layer = 1;
        for (i, requirement) in layout.layers.iter().enumerate() {
            if requirement.iter().all(|&(kind, held)| self.is_kind_held(kind) == held) {
                layer = i + 1;
                break;
            }
        }

        let shift_down = self.is_kind_held(ModKind::Shift);
        let mod4_down = self.is_kind_held(ModKind::Mod4);

        if capslock && layout.is_capslockable(scan) {
            if shift_down && layer == 2 {
                layer = 1;
            } else if !shift_down && layer == 1 {
                layer = 2;
            }
        }

        if self.mod4_lock {
            // Holding Mod4 switches back to layer 1, except in extension mode without filtered Neo modifiers: the real
            // Mod4 event would interfere with layer 1 keys there
            layer = if mod4_down && (self.config.filter_neo_modifiers || self.standalone) { 1 } else { 4 };
        }

        // For the OSK, Capslock simply swaps layers 1 and 2 of all keys
        let osk_layer = if capslock && (layer == 1 || layer == 2) { if shift_down { 2 } else { 1 } } else { layer };
        if osk_layer != self.osk_layer || capslock_changed {
            self.osk_layer = osk_layer;
            out.notice(Notice::OskChanged);
        }

        // Switching layers releases all held keys. Layers 1 and 2 count as one, so Shift doesn't release keys.
        let patched_layer = if layer == 2 { 1 } else { layer };
        if patched_layer != self.previous_patched_layer {
            let held = std::mem::take(&mut self.held_keys);
            for &(held_scan, key) in &held {
                self.send_key(key, held_scan, false, platform, out);
            }
            self.held_keys = held;
            self.held_keys.clear();
        }
        self.previous_patched_layer = patched_layer;

        if let Some(eat) = modifier_eaten {
            return eat;
        }
        if !self.layouts[layout_index].map.contains_key(&scan) {
            return false;
        }

        // In extension mode without filtered Neo modifiers only the layer 4 navigation keys that kbdneo lacks are
        // replaced
        let layer4_navigation_key = layer == 4
            && !scan.extended
            && matches!(scan.code, 0x09 | 0x10..=0x14 | 0x1E..=0x22 | 0x2C..=0x30);

        // Keys are swallowed and replaced in standalone and one-handed mode, for the numpad (kbdneo doesn't map it
        // according to spec), on layers 3 and up with filtered Neo modifiers, for the layer 4 navigation keys, and
        // with Mod4 lock (kbdneo has none)
        let replace = self.standalone
            || self.one_handed
            || numpad_key
            || (self.config.filter_neo_modifiers && layer >= 3)
            || layer4_navigation_key
            || (self.mod4_lock && !mod4_down);

        let key = KeyRef { layout: layout_index, scan, layer };
        if down {
            let neo_key = &self.layouts[layout_index].map[&scan].layers[layer - 1];
            match self.compose.compose(neo_key, &self.keysyms) {
                ComposeResult::Pass => {
                    self.set_held_key(scan, key);
                    if replace {
                        self.send_key(key, scan, true, platform, out);
                        return true;
                    }
                    false
                }
                ComposeResult::Eat => true,
                ComposeResult::Finish | ComposeResult::Abort => {
                    let text = self.compose.output();
                    send_text(text, out);
                    true
                }
            }
        } else {
            let held = self.take_held_key(scan);
            if replace {
                if let Some(held) = held {
                    self.send_key(held, scan, false, platform, out);
                }
                true
            } else {
                // Layer 1 and 2 keys that aren't held (swallowed by compose, or already released on a layer switch)
                held.is_none()
            }
        }
    }

    fn set_held_key(&mut self, scan: Scancode, key: KeyRef) {
        match self.held_keys.iter_mut().find(|(s, _)| *s == scan) {
            Some(entry) => entry.1 = key,
            None => self.held_keys.push((scan, key)),
        }
    }

    fn take_held_key(&mut self, scan: Scancode) -> Option<KeyRef> {
        let index = self.held_keys.iter().position(|(s, _)| *s == scan)?;
        Some(self.held_keys.swap_remove(index).1)
    }

    // ─── Sending ───────────────────────────────────────────────────────────────

    fn send_key(&mut self, key: KeyRef, real_scan: Scancode, down: bool, platform: &mut dyn Platform, out: &mut Output) {
        let neo_key = &self.layouts[key.layout].map[&key.scan].layers[key.layer - 1];
        let (keysym, action) = (neo_key.keysym, neo_key.action);
        if down {
            self.last_key = Some(key);
        }

        match action {
            // Mapped mouse click
            KeyAction::Vk { vk: vk::LBUTTON, .. } if keysym == KEYSYM_VOID => {
                out.inputs.push(Input::MouseLeft { down });
                out.end_batch();
            }
            KeyAction::Vk { vk: vk_code, mods } => {
                // Use the native layout's scancode if the key exists there
                let native = platform.vk_to_scan(vk_code);
                let scan = if native != 0 { Scancode::new(native, false) } else { real_scan };

                let forced = if down {
                    mods
                } else if self.last_key != Some(key) {
                    // Release of a key that didn't force the current modifiers: leave them
                    self.forced
                } else {
                    ForcedModifiers::NONE
                };
                self.send_vk_with_modifiers(vk_code, scan, forced, down, out);
            }
            KeyAction::Char(c) => {
                if self.standalone {
                    self.send_char_or_combo(c, down, platform, out);
                } else {
                    send_unicode(c, down, out);
                }
            }
        }
    }

    /// Sends a native key combination for the character if the native layout has one, else a Unicode packet
    fn send_char_or_combo(&mut self, c: char, down: bool, platform: &mut dyn Platform, out: &mut Output) {
        if u32::from(c) > 0xFFFF {
            send_unicode(c, down, out);
            return;
        }
        let Some(key) = platform.char_key(c, self.capslock) else {
            send_unicode(c, down, out);
            return;
        };

        let mut mods = ForcedModifiers::NONE;
        if down {
            // Always force Shift to the right state. Use a physically held Shift key if there is one.
            if key.shift {
                mods.set(if self.is_modifier_held(Modifier::RSHIFT) { Modifier::RSHIFT } else { Modifier::LSHIFT }, true);
            } else {
                mods.set(Modifier::LSHIFT, false);
                mods.set(Modifier::RSHIFT, false);
            }
            // AltGr is sent as LCtrl+RAlt. Characters without AltGr leave Ctrl and Alt alone, so shortcuts work.
            if key.altgr {
                mods.set(Modifier::LALT, false);
                mods.set(Modifier::RALT, true);
                mods.set(Modifier::LCTRL, true);
                mods.set(Modifier::RCTRL, false);
            }
        }
        self.send_vk_with_modifiers(key.vk, Scancode::new(key.scan, false), mods, down, out);
    }

    /// Sends a key and the minimal native modifier changes to reach the forced state, and remembers that state
    pub fn send_vk_with_modifiers(&mut self, vk_code: u16, mut scan: Scancode, forced: ForcedModifiers, down: bool, out: &mut Output) {
        let mut ups: [Option<Input>; 7] = [None; 7];
        let mut downs: [Option<Input>; 7] = [None; 7];
        let (mut up_count, mut down_count) = (0, 0);

        fn append(list: &mut [Option<Input>; 7], count: &mut usize, input: Input) {
            list[*count] = Some(input);
            *count += 1;
        }
        fn prepend(list: &mut [Option<Input>; 7], count: &mut usize, input: Input) {
            list.copy_within(0..*count, 1);
            list[0] = Some(input);
            *count += 1;
        }

        // Compare the state programs see ("resulting state") before and after applying the forced modifiers
        for modifier in NATIVE_MODIFIERS {
            let natural = self.is_modifier_held(modifier);
            let old = self.forced.get(modifier).unwrap_or(natural);
            let new = forced.get(modifier).unwrap_or(natural);
            let input = |down| Input::Key { vk: modifier.vk().unwrap(), scan: modifier.scancode().unwrap(), down };
            if old && !new {
                // Release RAlt first in case of LCtrl+RAlt
                if modifier == Modifier::RALT {
                    prepend(&mut ups, &mut up_count, input(false));
                } else {
                    append(&mut ups, &mut up_count, input(false));
                }
            } else if !old && new {
                // Press LCtrl first in case of LCtrl+RAlt
                if modifier == Modifier::LCTRL {
                    prepend(&mut downs, &mut down_count, input(true));
                } else {
                    append(&mut downs, &mut down_count, input(true));
                }
            }
        }
        self.forced = forced;

        scan.extended |= vk::is_extended(vk_code);
        let main = Input::Key { vk: vk_code, scan, down };
        if down {
            append(&mut downs, &mut down_count, main);
        } else {
            prepend(&mut ups, &mut up_count, main);
        }

        out.inputs.extend(ups[..up_count].iter().flatten());
        out.inputs.extend(downs[..down_count].iter().flatten());
        out.end_batch();
    }

    fn send_modifier(&mut self, modifier: Modifier, down: bool, out: &mut Output) {
        if let (Some(vk_code), Some(scan)) = (modifier.vk(), modifier.scancode()) {
            self.send_vk(vk_code, scan, down, out);
        }
    }

    fn send_vk(&mut self, vk_code: u16, mut scan: Scancode, down: bool, out: &mut Output) {
        scan.extended |= vk::is_extended(vk_code);
        out.inputs.push(Input::Key { vk: vk_code, scan, down });
        out.end_batch();
    }
}

fn opposite(modifier: Modifier) -> Modifier {
    Modifier { kind: modifier.kind, side: if modifier.side == Side::Left { Side::Right } else { Side::Left } }
}

/// A character as Unicode packet; characters outside of the BMP as surrogate pair in one batch
fn send_unicode(c: char, down: bool, out: &mut Output) {
    let mut units = [0u16; 2];
    for &unit in c.encode_utf16(&mut units).iter() {
        out.inputs.push(Input::Unicode { unit, down });
    }
    out.end_batch();
}

/// A string as Unicode packets, each code unit pressed and released
fn send_text(text: &str, out: &mut Output) {
    for unit in text.encode_utf16() {
        out.inputs.push(Input::Unicode { unit, down: true });
        out.inputs.push(Input::Unicode { unit, down: false });
    }
    out.end_batch();
}
